---
development:
  dialect: postgres
  database: learnbuffalo_pg_dev
  user: admin
  password: twilight
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/learnbuffalo_pg_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/learnbuffalo_pg_production?sslmode=disable"}}
